import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import Link from 'next/link'
import styles from '../styles/Home.module.css'
import NavBar from './NavBar'

const Home: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Ian Sornson</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1.0"></meta>
        <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css"></link>
        {/* <script src="https://kit.fontawesome.com/0d174862ad.js" crossOrigin="anonymous"></script> */}
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <NavBar/>
      <main className={styles.main}>
        <h1 className={styles.title}>
          Ian Sornson
        </h1>
        <p className={styles.description}>
          Computer Science student at the <span className={styles.uiuc}>University of 
          Illinois at Urbana-Champaign</span>.
        </p>
        <div className={styles.socials}>
          <Link href="https://github.com/Sorsmo">
            <a className={styles.social} target="_blank">
              <i className="fa fa-github"></i>
            </a>
          </Link>
        </div>
      </main>
      <div className={styles.divider} id='about'></div>
      <section className={styles.section}>
        <h1 className={styles.header}>About Me</h1>
        <p className={styles.details}>
          I&apos;m Ian, a Sophomore at the University of Illinois at Urbana-Champaign
          pursuing a B.S. in Computer Science with an expected graduation date of May 2025. I am currently seeking a Summer 2024 software engineering internship.
          I am passionate about <strong>quantitative finance</strong>, <strong>artificial intelligence</strong>, 
          <strong>machine learning</strong>, <strong> computer vision</strong>, and <strong>autonomous robots</strong>. 
          <br/>
          <br/>
          Currently, I am working at Cognautica, a startup developing automatic grading solutions for a learning management system using computer vision and natural language processing. 
          I am working closely with OpenAI&apos;s GPT-4 to accurately grade student exam responses across many subjects. 
          Previously, I was a Technical Lead for the Disruption Lab at Gies, an incubator where students work with entrepreneurs and researchers to solve real industry problems, 
          heading the development of a blockchain based access system to protect sensitive State of Illinois personal identifiable information and HIPAA data utilizing NFTs, 
          smart contracts, and AWS.
        </p>
      </section>

      <div className={styles.divider} id='projects'></div>
      <section className={styles.section}>
        <h1 className={styles.header}>Projects</h1>
        <div className={styles.grid}>
          {/* <Link href=""> */}
            <a className={styles.card} target="_blank">
              <div className={styles.cardHeader}>
                <h2 className={styles.projectName}>Algorithmic Trading Bot</h2>
                <Image className={styles.cardImage} src="/trading.jpg" alt="port" width={300} height={200} />
              </div>
              <div className={styles.cardBox}>
                <p className={styles.cardDetails}>
                  Coming soon!
                </p>
              </div>
            </a>
          {/* </Link> */}

          <Link href="https://github.com/Sorsmo/gtav-neural-net">
            <a className={styles.card} target="_blank">
              <div className={styles.cardHeader}>
                <h2 className={styles.projectName}>Self-Driving Car in Grand Theft Auto V</h2>
                <Image className={styles.cardImage} src="/gtav.jpg" alt="port" width={300} height={200} />
              </div>
              <div className={styles.cardBox}>
                <p className={styles.cardDetails}>
                  A self driving car in GTAV trained with a convolution neural network using <strong>Tensorflow</strong>, <strong>OpenCV</strong>, and <strong>Python</strong>.
                </p>
              </div>
            </a>
          </Link>

          <Link href="https://github.com/Sorsmo/chess-engine">
            <a className={styles.card} target="_blank">
              <div className={styles.cardHeader}>
                <h2 className={styles.projectName}>&quot;YanNepocho&quot; Chess Engine</h2>
                <Image className={styles.cardImage} src="/yan.png" alt="port" width={300} height={200} />
              </div>
              <div className={styles.cardBox}>
                <p className={styles.cardDetails}>
                  A chess engine integrated with the <strong>LiChess API</strong> for online play. Developed using <strong>Python</strong>.
                </p>
              </div>
            </a>
          </Link> 

          <Link href="https://fourhead.vercel.app/">
            <a className={styles.card} target="_blank">
              <div className={styles.cardHeader}>
                <h2 className={styles.projectName}>Headlines</h2>
                <Image className={styles.cardImage} src="/headlines2.png" alt="Headlines" width={300} height={200} />
              </div>
              <div className={styles.cardBox}>
                <p className={styles.cardDetails}>
                  Fourheads is a collection of web games that test your vocabulary and knowledge of the world. 
                  Built using <strong>JavaScript</strong>, <strong>Next.js</strong>, <strong>Typescript</strong>, and 
                  the <strong>New York Times API</strong>. 
                </p>
              </div>
            </a>
          </Link>

          <Link href="https://ambermusic.netlify.app">
            <a className={styles.card} target="_blank">
              <div className={styles.cardHeader}>
                <h2 className={styles.projectName}>Amber</h2>
                <Image className={styles.cardImage} src="/ambermusic2.png" alt="ambermusic" width={300} height={200} />
              </div>
              <div className={styles.cardBox}>
                <p className={styles.cardDetails}>
                  Amber is a music oriented guessing game fueled by 
                  your own Spotify stats. How well do you know yourself? Built using <strong>JavaScript</strong>, <strong>React.js</strong>, 
                  {" "}<strong>Axios</strong>, and the <strong>Spotify SDK</strong>.
                </p>
              </div>
            </a>
          </Link>

          <Link href="https://iansornson.vercel.app">
            <a className={styles.card} target="_blank">
              <div className={styles.cardHeader}>
                <h2 className={styles.projectName}>My Portfolio</h2>
                <Image className={styles.cardImage} src="/port2.png" alt="port" width={300} height={200} />
              </div>
              <div className={styles.cardBox}>
                <p className={styles.cardDetails}>
                  I mean it counts doesn&apos;t it? Built using <strong>JavaScript</strong>,  
                  {" "}<strong>Next.js</strong>, and <strong>Typescript</strong>.
                </p>
              </div>
            </a>
          </Link>
        </div>
      </section>

      {/* <div className={styles.divider} id="contact"></div>
      <section className={styles.section}>
        <h1 className={styles.header}>Contact Me</h1>
        <p className={styles.details}>
        </p>
      </section> */}
      <footer>
        <span className={styles.footer}>
          <a href='mailto:iansornson55@gmail.com'>
            Email me! (iansornson55@gmail.com)
          </a>
        </span>
      </footer>
    </div>
  )
}

export default Home;